import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-mobile-pattern sm:bg-desktop-pattern bg-[#FF7979]">
        {children}
      </body>
    </html>
  );
}
